### ISSUE TITLE
執筆する本の内容を決める

### ISSUE THREAD

**Issue by ojiry** [otaku-dev/techbookfest#1]
## 目的
次の技術書店に向けて書いていく本の内容を決める
## 前提
- 対象読者を決める（読者の習熟度、技術背景など）
- 既に出版してある本と被るネタは避ける（並行処理、インタプリタなど）
- 出版形式を決める（紙 or 紙 + PDF）
## 検討案
- SILO を Go で実装する
- Go + XXX（KubernetesとかGCPとか）
- Go の時期バージョンにある新機能

**Comment by yuukigoodman** [comment]
@ojiry SILOは難度が高く見積もりにくいので、個人的な別作業とさせてください。
それ以外の検討案から良さそうな物を選びましょう

**Comment by pankona** [comment]
2019/05/01 MTG での執筆テーマ検討のメモ

- Kubernetes で動かす Go アプリケーション (仮)
  - 以下、全て含めるかはさておき、こんなトピックを扱ったらいいのではないかという案
    - Go + Kubernetes
    - どのように container を作っていくか、みたいな
    - Web アプリケーションをリッチに作るチュートリアル
    - 認証、API、CRUD へのアクセスなども盛り込む
    - Kubernetes を使っていく
    - CI、CD あたりまで含めていく
    - gRPC も入れちゃう
    - Istio も入れちゃう

- 対象読者の件
  - 単体技術としては知っているが、本番運用していく周りの知見に乏しいような人には刺さるかも
  - つまり自分たちのため…！(ここ重要)

- 執筆とあわせて、何かサンプルアプリを作る必要がありそうな
  - 何を作る？っていうのもぼちぼち考えていく

**Comment by ojiry** [comment]
内容は仮だけど決まったのでこの Issue はクローズ
