### ISSUE TITLE
キックオフを開催する

### ISSUE THREAD

**Issue by ojiry** [otaku-dev/techbookfest#3]
## 目的
作業を円滑に進めるため、 Discord の音声チャットでキックオフを開催する

## やること
- [x] 各自の空いている日を確認
- [x] 日程を決める
- [x] アジェンダを作成する
- [x] キックオフを開催する

**Comment by pankona** [comment]
2019/05/01 15:00〜 キックオフを開催した。
使った資料は以下。
https://docs.google.com/document/d/1hruZVWtAkyohuowVOJUnCt6WyGw4EcReQ36DM8WfnCg/edit#
